import { Geist_Mono, Outfit } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

import {
  ClerkProvider,
} from '@clerk/nextjs'
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<ClerkProvider>
    <html lang="en">
        <body className={`${outfit.variable} ${geistMono.variable} antialiased`}>
        <Toaster richColors position="top-right" />
          {children}
        </body>
      
    </html>
    </ClerkProvider>
  );
}
